In [1]:
import pandas as pd

wine_df = pd.read_csv("winequality-red.csv", sep=";")

In [2]:
wine_df.head()

,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol,quality
0,7.4,0.70,0.00,1.9,0.076,11.0,34.0,0.9978,3.51,0.56,9.4,5
1,7.8,0.88,0.00,2.6,0.098,25.0,67.0,0.9968,3.20,0.68,9.8,5
2,7.8,0.76,0.04,2.3,0.092,15.0,54.0,0.9970,3.26,0.65,9.8,5
3,11.2,0.28,0.56,1.9,0.075,17.0,60.0,0.9980,3.16,0.58,9.8,6
4,7.4,0.70,0.00,1.9,0.076,11.0,34.0,0.9978,3.51,0.56,9.4,5

In [3]:
print(wine_df["pH"].count())

1599

In [4]:
print(wine_df["pH"].mean())
print(wine_df["pH"].median())

3.3111131957473416
3.31

In [5]:
print(wine_df["pH"].min())
print(wine_df["pH"].max())

2.74
4.01

In [6]:
print(wine_df["fixed acidity"].min())

4.6

In [7]:
print(wine_df["fixed acidity"].max())

15.9

In [8]:
print(wine_df["fixed acidity"].mean())
print(wine_df["fixed acidity"].median())

8.31963727329581
7.9

In [9]:
cat_groups = (wine_df.groupby("quality")
              .agg(
    wine_count=("pH","count"),
    alcohol_mean = ("alcohol","mean"),
    alcohol_min = ("alcohol","min"),
    alcohol_max = ("alcohol","max")
)
              .reset_index())

In [10]:
print(cat_groups)

   quality  wine_count  alcohol_mean  alcohol_min  alcohol_max
0        3          10      9.955000          8.4         11.0
1        4          53     10.265094          9.0         13.1
2        5         681      9.899706          8.5         14.9
3        6         638     10.629519          8.4         14.0
4        7         199     11.465913          9.2         14.0
5        8          18     12.094444          9.8         14.0

In [11]:
import pandas as pd

magic_df = pd.read_csv("all_mtg_cards.csv", low_memory=False)

In [12]:
magic_df.head()

,name,multiverse_id,layout,names,mana_cost,cmc,colors,color_identity,type,supertypes,...,foreign_names,printings,original_text,original_type,legalities,source,image_url,set,set_name,id
0,Ancestor's Chosen,130550.0,normal,NaN,{5}{W}{W},7.0,['W'],['W'],Creature — Human Cleric,NaN,...,"[{'name': 'Ausgewählter der Ahnfrau', 'text': ...","['10E', 'JUD', 'UMA']",First strike\nWhen Ancestor's Chosen comes int...,Creature - Human Cleric,"[{'format': 'Commander', 'legality': 'Legal'},...",NaN,http://gatherer.wizards.com/Handlers/Image.ash...,10E,Tenth Edition,5f8287b1-5bb6-5f4c-ad17-316a40d5bb0c
1,Ancestor's Chosen,NaN,normal,NaN,{5}{W}{W},7.0,['W'],['W'],Creature — Human Cleric,NaN,...,NaN,"['10E', 'JUD', 'UMA']",NaN,NaN,"[{'format': 'Commander', 'legality': 'Legal'},...",NaN,NaN,10E,Tenth Edition,b7c19924-b4bf-56fc-aa73-f586e940bd42
2,Angel of Mercy,129465.0,normal,NaN,{4}{W},5.0,['W'],['W'],Creature — Angel,NaN,...,"[{'name': 'Engel der Gnade', 'text': 'Fliegend...","['10E', '8ED', '9ED', 'DDC', 'DVD', 'IMA', 'IN...","Flying\nWhen Angel of Mercy comes into play, y...",Creature - Angel,"[{'format': 'Brawl', 'legality': 'Legal'}, {'f...",NaN,http://gatherer.wizards.com/Handlers/Image.ash...,10E,Tenth Edition,57aaebc1-850c-503d-9f6e-bb8d00d8bf7c
3,Angel of Mercy,NaN,normal,NaN,{4}{W},5.0,['W'],['W'],Creature — Angel,NaN,...,NaN,"['10E', '8ED', '9ED', 'DDC', 'DVD', 'IMA', 'IN...",NaN,NaN,"[{'format': 'Brawl', 'legality': 'Legal'}, {'f...",NaN,NaN,10E,Tenth Edition,8fd4e2eb-3eb4-50ea-856b-ef638fa47f8a
4,Angelic Blessing,129711.0,normal,NaN,{2}{W},3.0,['W'],['W'],Sorcery,NaN,...,"[{'name': 'Himmlischer Segen', 'text': 'Eine K...","['10E', '9ED', 'EXO', 'P02', 'POR', 'PS11', 'S...",Target creature gets +3/+3 and gains flying un...,Sorcery,"[{'format': 'Commander', 'legality': 'Legal'},...",NaN,http://gatherer.wizards.com/Handlers/Image.ash...,10E,Tenth Edition,55bd38ca-dc73-5c06-8f80-a6ddd2f44382

In [13]:
magic_df["name"].nunique()

29049

In [24]:
# cat_groups = (magic_df.groupby("cmc")
#               .agg(
#     max_cost = ("cmc", "max"),
#     min_cost = ("cmc", "min"),
#     mean_cost = ("cmc", "mean"),
#
# ))

cat_groups = (magic_df.groupby("layout")
              .agg(
    max_cost = ("colors", "nunique"),
    name = ("name", "max"),

))

cat_groups

                 max_cost                                            name
layout
adventure               8               Young Red Dragon // Bathe in Gold
aftermath               5                             Struggle // Survive
augment                 5                                       Zombified
case                    5                       Case of the Uneaten Feast
class                  10                                    Wizard Class
flip                    5  Student of Elements // Tobita, Master of Winds
host                    5                                  Wild Crocodile
leveler                 5                               Zulaport Enforcer
meld                    6                              Urza, Planeswalker
modal_dfc               9                 Zof Consumption // Zof Bloodbog
mutate                 15                                       Vulpikeet
normal                 35                             Éowyn, Shieldmaiden
planar                  0                              Windriddle Palaces
prototype               0                            Woodcaller Automaton
reversible_card         9                  Zombie Master // Zombie Master
saga                   19                              Yotia Declares War
scheme                  0                       Your Will Is Not Your Own
split                  15             Who // What // When // Where // Why
transform              21              Wolfkin Outcast // Wedding Crasher
vanguard                0                                         Xantcha

In [29]:
magic_df["type"].value_counts(normalize=True)[:10]

type
Sorcery                     0.104898
Instant                     0.104172
Artifact                    0.053469
Enchantment                 0.052529
Land                        0.052465
Enchantment — Aura          0.032239
Artifact — Equipment        0.012868
Creature — Human Wizard     0.011330
Creature — Elemental        0.010391
Creature — Human Soldier    0.009878
Name: proportion, dtype: float64

In [30]:
magic_df["layout"].value_counts(normalize=True)[:10]

layout
normal       0.949030
transform    0.018304
adventure    0.007069
modal_dfc    0.005831
split        0.003780
planar       0.002873
saga         0.002755
aftermath    0.002029
mutate       0.001580
vanguard     0.001271
Name: proportion, dtype: float64

In [38]:
magic_df.iloc[0]["legalities"]

"[{'format': 'Commander', 'legality': 'Legal'}, {'format': 'Duel', 'legality': 'Legal'}, {'format': 'Legacy', 'legality': 'Legal'}, {'format': 'Modern', 'legality': 'Legal'}, {'format': 'Oathbreaker', 'legality': 'Legal'}, {'format': 'Paupercommander', 'legality': 'Restricted'}, {'format': 'Penny', 'legality': 'Legal'}, {'format': 'Predh', 'legality': 'Legal'}, {'format': 'Premodern', 'legality': 'Legal'}, {'format': 'Vintage', 'legality': 'Legal'}]"

In [40]:
grouping = (magic_df
          .groupby(["layout", "colors"])
          .agg(
            avg_cmc = ("cmc", "mean"),
            num_trips = ("colors", "count")
          ))

print(grouping)

                            avg_cmc  num_trips
layout    colors
adventure ['B']            3.234234        111
          ['G']            4.103448        145
          ['R']            3.561905        105
          ['U', 'G']       3.800000         10
          ['U', 'R', 'G']  3.000000          8
...                             ...        ...
transform ['R', 'W']       2.636364         11
          ['R']            3.283401        247
          ['U', 'W']       2.538462         52
          ['U']            2.785408        233
          ['W']            2.825000        200

[177 rows x 2 columns]

In [56]:
weed_df = pd.read_csv("kushy-cannabis-dataset/versions/1/products-kushy_api.2017-11-14.csv")

In [57]:
weed_df

,id,name,slug,brand,category,strain,thc,cbd,lab_test
0,1,Pre-Roll Package - Pre-roll,the-humboldt-cure-pre-roll-package-pre-roll,The Humboldt Cure,"Flowers,Pre-Roll",NaN,NaN,NaN,NaN
1,2,ounce of cannabis,the-humboldt-cure-ounce-of-cannabis,The Humboldt Cure,NaN,NaN,NaN,NaN,NaN
2,3,1/2 ounce of cannabis,the-humboldt-cure-1-2-ounce-of-cannabis,The Humboldt Cure,NaN,NaN,NaN,NaN,NaN
3,4,1/4 ounce of cannabis,the-humboldt-cure-1-4-ounce-of-cannabis,The Humboldt Cure,NaN,NaN,NaN,NaN,NaN
4,5,1/8,the-humboldt-cure-1-8,The Humboldt Cure,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...
17228,17229,Blueberry - Oil,popnaturals-blueberry-oil,PopNaturals,"Concentrate,Oil,",Blueberry,NaN,NaN,NaN
17229,17230,Purple Haze - Oil,popnaturals-purple-haze-oil,PopNaturals,"Concentrate,Oil,",Purple Haze,NaN,NaN,NaN
17230,17231,Cannatonic - Oil,popnaturals-cannatonic-oil,PopNaturals,"Concentrate,Oil,",Cannatonic,19.71%,33%,https://www.cannabisreports.com/lab-tests/f/fc...
17231,17232,Pineapple Kush - Wax,unknown-producer-pineapple-kush-wax,Unknown Producer,"Concentrate,Wax,",Pineapple Kush,NaN,NaN,NaN
17232,17233,Chocolate Thai - Wax,unknown-producer-chocolate-thai-wax,Unknown Producer,"Concentrate,Wax,",Chocolate Thai,NaN,NaN,NaN

In [96]:
grouping = (weed_df
            .groupby(["strain","category"])
            .agg(
                 strain_count = ("strain", "count"),
                 name_count = ("name", "count"))
            .reset_index())
print(grouping)

                                                 strain  \
0     (Early Pearl/Skunk No. 1/Northern Lights #5) x...
1     (Early Pearl/Skunk No. 1/Northern Lights #5) x...
2                                        (Many Strains)
3                                        (Many Strains)
4                                              18:1 CBD
...                                                 ...
5342                                   Zkittlez/Cookies
5343                              Zkittlez/OG Eddy Lepp
5344                                  Zombie Girl Scout
5345                                          Zombie OG
5346                                          Zombie OG

                      category  strain_count  name_count
0     Concentrate,Crumble,Wax,             1           1
1             Concentrate,Oil,             1           1
2     Concentrate,Bubble Hash,             2           2
3             Concentrate,Oil,             1           1
4             Concentrate,Oil,             1           1
...                        ...           ...         ...
5342  Concentrate,Bubble Hash,             1           1
5343  Concentrate,Bubble Hash,             1           1
5344          Concentrate,Oil,             1           1
5345  Concentrate,Crumble,Wax,             1           1
5346          Concentrate,Wax,             1           1

[5347 rows x 4 columns]